# ============================================================
# IGNACIO: Bow-at-Banff Configuration
# ============================================================
# Configured for the actual test data in ./data directory
# ============================================================

project:
  name: "Bow_at_Banff"
  description: "Fire growth simulation for Bow River basin near Banff"
  output_dir: "./output"
  random_seed: 42

crs:
  working_crs: "EPSG:4326"  # Match DEM CRS
  output_crs: "EPSG:4326"   # Match DEM CRS

terrain:
  dem_path: "./data/DEM.tif"
  slope_path: null
  aspect_path: null

fuel:
  source_type: "raster"
  path: "./data/fuels.tif"
  non_fuel_codes: [0, 100, 101, 102, 103, 104, 105, 106, -9999]
  fuel_lookup:
    # Standard FBP fuel types
    1: "C-1"    # Spruce-Lichen Woodland
    2: "C-2"    # Boreal Spruce
    3: "C-3"    # Mature Jack or Lodgepole Pine
    4: "C-4"    # Immature Jack or Lodgepole Pine
    5: "C-5"    # Red and White Pine
    6: "C-6"    # Conifer Plantation
    7: "C-7"    # Ponderosa Pine / Douglas Fir
    11: "D-1"   # Leafless Aspen
    12: "D-1"   # Green Aspen (D-2, treated as D-1)
    13: "D-1"   # D-1/D-2 Aspen
    21: "S-1"   # Jack or Lodgepole Pine Slash
    22: "S-2"   # White Spruce / Balsam Slash
    23: "S-3"   # Coastal Cedar / Hemlock / Douglas-Fir Slash
    31: "O-1a"  # Matted Grass
    32: "O-1b"  # Standing Grass
    40: "M-1"   # Boreal Mixedwood - Leafless
    50: "M-2"   # Boreal Mixedwood - Green
    60: "M-1"   # M-1/M-2 Boreal Mixedwood
    70: "M-3"   # Dead Balsam Fir Mixedwood - Leafless
    80: "M-4"   # Dead Balsam Fir Mixedwood - Green
    90: "M-3"   # M-3/M-4 Dead Balsam Fir Mixedwood
    # Non-fuel types
    100: "NF"   # Not Available
    101: "NF"   # Non-fuel
    102: "WA"   # Water
    103: "NF"   # Unknown
    104: "NF"   # Unclassified
    105: "NF"   # Vegetated Non-Fuel
    106: "NF"   # Urban or built-up area
    # M-1 Boreal Mixedwood - Leafless (with % conifer encoded)
    405: "M-1"
    410: "M-1"
    415: "M-1"
    420: "M-1"
    425: "M-1"
    430: "M-1"
    435: "M-1"
    440: "M-1"
    445: "M-1"
    450: "M-1"
    455: "M-1"
    460: "M-1"
    465: "M-1"
    470: "M-1"
    475: "M-1"
    480: "M-1"
    485: "M-1"
    490: "M-1"
    495: "M-1"
    # M-2 Boreal Mixedwood - Green (with % conifer encoded)
    505: "M-2"
    510: "M-2"
    515: "M-2"
    520: "M-2"
    525: "M-2"
    530: "M-2"
    535: "M-2"
    540: "M-2"
    545: "M-2"
    550: "M-2"
    555: "M-2"
    560: "M-2"
    565: "M-2"
    570: "M-2"
    575: "M-2"
    580: "M-2"
    585: "M-2"
    590: "M-2"
    595: "M-2"
    # M-1/M-2 Boreal Mixedwood (with % conifer encoded)
    605: "M-1"
    610: "M-1"
    615: "M-1"
    620: "M-1"
    625: "M-1"
    630: "M-1"
    635: "M-1"
    640: "M-1"
    645: "M-1"
    650: "M-1"
    655: "M-1"
    660: "M-1"
    665: "M-1"
    670: "M-1"
    675: "M-1"
    680: "M-1"
    685: "M-1"
    690: "M-1"
    695: "M-1"
  
  # Custom mapping to Rothermel fuel models (optional)
  # If using engine: rothermel, these override the default FBP-to-Rothermel mapping
  # Uncomment and customize if needed:
  # rothermel_fuel_mapping:
  #   1: 8      # C-1 -> Compact timber litter
  #   2: 10     # C-2 -> Timber understory
  #   3: 9      # C-3 -> Hardwood litter
  #   4: 10     # C-4 -> Timber understory
  #   31: 1     # O-1a -> Short grass
  #   32: 3     # O-1b -> Tall grass

# --- Ignition from shapefile ---
ignition:
  source_type: "shapefile"
  point_path: "./data/Ignition_A.shp"
  cause: "Lightning"
  season: "Summer"
  n_iterations: 1
  escaped_fire_distribution:
    1: 1.0

# --- Weather Configuration ---
# The Bow_FWI_out.csv has pre-calculated FWI components
# ISI values in this dataset range from ~1.5 to ~7.3
# Adjusting thresholds accordingly
weather:
  # stations.csv contains hourly weather observations (TEMP, RH, WS, WD, PRECIP)
  # FWI will be calculated automatically from this data
  station_path: "./data/stations.csv"
  weather_path: null  # Use station_path for weather data
  
  # Enable automatic FWI calculation from hourly weather
  calculate_fwi: true
  fwi_latitude: 51.35  # Latitude for day length adjustment in FWI calc
  
  weather_columns:
    datetime: "HOURLY"
    temperature: "TEMP"
    relative_humidity: "RH"
    wind_speed: "WS"
    wind_direction: "WD"
    precipitation: "PRECIP"
  
  datetime_format: "%d/%m/%Y"
  
  # ISI thresholds for fire danger classification
  # Adjusted for calculated FWI from hourly weather (ISI range ~0-7)
  isi_thresholds:
    moderate: 0.0
    high: 3.0      # Lowered to capture more fire-conducive days
    extreme: 6.0   # Lowered proportionally
  
  filter_conditions: ["moderate", "high", "extreme"]
  spread_event_lambda: 3.76

fbp:
  defaults:
    ffmc: 88.0    # Higher FFMC for drier fine fuels
    dmc: 30.0     # Moderate duff moisture
    dc: 150.0     # Moderate drought
    isi: 5.0      # Moderate-high ISI
    bui: 50.0     # Moderate-high BUI
    fwi: 15.0     # Moderate-high FWI
  fmc: 100.0
  curing: 85.0
  slope_factor: 0.5
  backing_fraction: 0.2
  length_to_breadth: 2.0
  
  # Fire model selection
  model:
    engine: fbp                    # 'fbp' (Canadian) or 'rothermel' (US/FARSITE)
    rothermel_fuel_model_set: both # '13' (Anderson), '40' (Scott-Burgan), or 'both'
    midflame_wind_reduction: 0.4   # Factor to reduce 10m wind to midflame height

# --- JAX Calibration Configuration ---
# Enable this to use differentiable JAX backend for calibration
calibration:
  enabled: false            # Set to true to enable JAX calibration
  use_jax_simulation: false # Set to true to use JAX for all simulations
  
  # Parameters to calibrate
  calibrate_wind: true      # Wind speed adjustment factor
  calibrate_ffmc: true      # Fuel moisture adjustment
  calibrate_ros_scale: false
  calibrate_backing: false
  
  # Initial values (starting point for optimization)
  wind_adj_init: 1.0        # 1.0 = no adjustment
  ffmc_adj_init: 0.0        # 0.0 = no adjustment
  ros_scale_init: 1.0
  backing_frac_init: 0.2
  
  # Calibrated values (populated after calibration, or set manually)
  wind_adj: 1.0
  ffmc_adj: 0.0
  ros_scale: 1.0
  backing_frac: 0.2
  
  # Optimization settings
  learning_rate: 0.1        # Adam learning rate
  n_iterations: 100         # Maximum iterations
  convergence_tol: 0.000001 # Stop when loss change < tol
  regularization: 0.01      # L2 regularization strength
  
  # Parameter bounds (min, max)
  wind_adj_bounds: [0.3, 3.0]
  ffmc_adj_bounds: [-15.0, 15.0]
  ros_scale_bounds: [0.3, 3.0]
  backing_frac_bounds: [0.05, 0.5]

simulation:
  dt: 1.0
  max_duration: 480  # 8 hours
  n_vertices: 300
  initial_radius: 10.0  # 10 meter initial fire
  store_every: 10
  min_ros: 0.01
  
  # Time-varying weather (uses hourly weather data)
  time_varying_weather: true
  start_datetime: "2024-07-15 12:00:00"  # Mid-July noon start
  default_start_hour: 12  # Noon if no datetime specified

output:
  save_perimeters: true
  save_ros_grids: true
  save_weather_summary: true
  save_ignition_summary: true
  perimeter_format: "shapefile"
  combine_perimeters: true
  generate_plots: true
  generate_animation: false
  log_level: "INFO"
